accent = "#F095C8"
cursor = "#FFB1DD"
foreground = "#F6EFF3"
background = "#1A1218"
selection_foreground = "#F6EFF3"
selection_background = "#342230"

color0 = "#1A1218"
color1 = "#FF718F"
color2 = "#B4E7C7"
color3 = "#F2B86D"
color4 = "#F095C8"
color5 = "#FFB1DD"
color6 = "#A9C7EE"
color7 = "#F6EFF3"
color8 = "#342230"
color9 = "#FF718F"
color10 = "#B4E7C7"
color11 = "#E0C27A"
color12 = "#C4DAF6"
color13 = "#FFB1DD"
color14 = "#D7A0B8"
color15 = "#F6EFF3"
